Add mandatory features for Livedata release
xwiki/xwiki-platform pull request #1470
Opened 2020-11-26 09:19 UTC by ClemDee

Add date and suggest filters for the Livedata

2020-11-26 11:36 UTC, ClemDee commented
Actually don't pay attention to the two commits named "mend". Those are just "--amend" commits I failed somehow and didn't see until now.

2020-12-10 11:06 UTC, mflorea requested changes

2020-12-10 11:06 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/filters/FilterSuggest.vue
> +        hint: metaData.hint,
This should be handled by the live data source. ``logic.getPropertyValues()`` should return ``{value, label, icon, url, hint}``. See below.

2020-12-10 12:48 UTC, mflorea requested changes

2020-12-10 12:48 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/filters/FilterSuggest.vue
> +    // Taken from xwiki-platform-web/src/main/webapp/resources/uicomponents/suggest/xwiki.selectize.js
I don't like this. We should instead find a way to trigger this code from the ``xwiki.selectize.js``. One idea is to add an event that ``xwiki.selectize.js`` listen to and reloads the selected values as a result. ATM ``xwiki.selectize.js`` loads the selected values only when initialized. But someone could change the value afterwards. The simplest solution I see is to modify ``xwiki.selectize.js`` to listen to ``change`` event on the underlying input/select and to reload the selected values when this happens. With this we will only have to trigger the ``change`` event from the live data filter.

2020-12-10 12:48 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/filters/FilterSuggest.vue
> +      });
This looks like a hack. As mentioned above, I think it should be enough to trigger an event that reloads the selected values from ``xwiki.selectize.js``.

2020-12-10 12:48 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/filters/filterMixin.js
> +      if (this._applyFilterTimeoutId) {
This ``if`` is not needed. ``clearTimeout`` is null safe AFAIK.

2020-12-10 12:48 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/webjar/Logic.js
> +        // return this.isEditable({ entry });
You should check if the entry has a value set for the configured id property (from the entry descriptor). We can't select entries that don't have an id. Then, if the id is specified we look at the configuration (TODO).

2020-12-14 14:22 UTC, merged