XWIKI-17428 Use translation keys in the live data UI
xwiki/xwiki-platform pull request #1594
Opened 2021-04-09 11:13 UTC by ClemDee

* The date filter has not been translated, as it is related to XWIKI-18535

2021-04-09 11:14 UTC, ClemDee commented
The current mock data used for tests is:
```json
{
  "livedata.dropdownMenu.title": "More Actions",
  "livedata.dropdownMenu.changeLayout": "Change Layout",
  "livedata.dropdownMenu.header.panels": "Panels",
  "livedata.dropdownMenu.panels.properties": "Advanced Properties",
  "livedata.dropdownMenu.panels.sorting": "Advanced Sorting",
  "livedata.dropdownMenu.panels.filtering": "Advanced Filtering",

  "livedata.selection.selectInAllPages": "Select in all pages",
  "livedata.selection.infoBar.selectedCount": "{0} entries selected",
  "livedata.selection.infoBar.allSelected": "All entries selected",
  "livedata.selection.infoBar.allSelectedBut": "All entries selected but {0}",

  "livedata.pagination.currentEntries": "Entries {0} - {1} out of {2}",
  "livedata.pagination.pageSize": "per page of",
  "livedata.pagination.page": "page",
  "livedata.pagination.first": "First page",
  "livedata.pagination.previous": "Previous page",
  "livedata.pagination.next": "Next page",
  "livedata.pagination.last": "Last page",

  "livedata.refresh": "Refresh",
  "livedata.addEntry": "Add entry",

  "livedata.panel.filter.title": "Filter",
  "livedata.panel.filter.noneFilterable": "None of the displayed properties is filterable.",
  "livedata.panel.filter.add": "+ Add Filter",
  "livedata.panel.filter.addProperty": "Add Filter",
  "livedata.panel.filter.delete": "Delete filters",
  "livedata.panel.filter.deleteAll": "Delete the whole property filters",

  "livedata.panel.properties.title": "Properties",

  "livedata.panel.sort.title": "Sort",
  "livedata.panel.sort.noneSortable": "None of the displayed properties is sortable.",
  "livedata.panel.sort.direction.ascending": "Ascending",
  "livedata.panel.sort.direction.descending": "Descending",
  "livedata.panel.sort.add": "Add Sort level",
  "livedata.panel.sort.delete": "Delete sort",

  "livedata.layouts.table.title": "Table",
  "livedata.layouts.cards.title": "Cards",

  "livedata.dislayer.link.noValue": "(no value)",
}
```

2021-04-15 09:23 UTC, mflorea requested changes

2021-04-15 09:23 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/LivedataDropdownMenu.vue
> +          {{ $t(`livedata.layout.${layout.id}.title`) }}
The layout name was already translated so this change is not needed.

2021-04-15 09:23 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/displayers/DisplayerActions.vue
> +          :title="$t(`livedata.displayer.actions.${action.id}`)"
The action description was already translated so this change is not needed.

2021-04-15 09:23 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/displayers/DisplayerActions.vue
> +    });
This doesn't seem to be used here but in link displayer below.

2021-04-15 09:23 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/displayers/DisplayerLink.vue
> +    });
This doesn't seem to be used here but above in actions displayer (where it's actually not needed).

2021-04-15 09:23 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/cards/LayoutCards.vue
> +  },
Not needed because the layout title is already translated.

2021-04-15 09:23 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/layouts/table/LayoutTable.vue
> +  },
Not needed because the layout title is already translated (it is part of the live data descriptor).

2021-04-15 09:31 UTC, mflorea requested changes

2021-04-15 09:31 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/vue/panels/LivedataAdvancedPanelFilter.vue
> +            {{ $t('livedata.panel.filter.add') }}
I would use "Add constraint".

2021-04-15 09:31 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/webjar/Logic.js
> +      const url = baseUrl + localeParam + prefixParam + keysParam;
This needs to be adapted to use the REST URL.

2021-04-15 09:31 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/webjar/Logic.js
> +        i18n.mergeLocaleMessage(lang, messages)
The JSON response needs to be adapted.

2021-04-15 09:31 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/webjar/Logic.js
> +          .map(layoutDescriptor => `layout.${ layoutDescriptor.id }.title`),
This is not needed.

2021-04-15 10:03 UTC, merged

2021-04-15 10:03 UTC, mflorea commented
I merge it and I'm going to fix the remaining issues myself so that we can have it in 13.3RC1.