XWIKI-19651: Introduce the grid attachment picker macro
xwiki/xwiki-platform pull request #1832
Opened 2022-05-03 07:25 UTC by manuelleduc

This is currently a draft PR  of my work on https://jira.xwiki.org/browse/XWIKI-19651

- The code is not located in the right module and will be moved to `xwiki-platform-attachment-picker`
- Some core feature are missing:
  - selecting an attachment
  - notifying external listeners that an attachment has been selecting with an event
  - integration of a popover to open the lightbox

2022-05-04 15:08 UTC, manuelleduc commented
> * I don't understand why the user has to click "back", that doesn't seem intuitive.

Indeed, I could update it to "Change Image" (along what we hare for the macro edition modal, where we use "Change Macro")

> * The tab named "Attachment picker" doesn't seem that good. There's a "Document Tree" one next to it which is also an attachment picker. I'd use either:
>   
>   * "Search" and "Tree"
>   * or "Gallery" and "Tree" (since both support searching)
>   * or "Attachment Search" and "Page Tree" (note that we're not supposed to use "Document" in the UI ;))

+1 for "Gallery" and "Tree"

2022-05-06 15:43 UTC, manuelleduc commented on xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-picker/xwiki-platform-attachment-picker-test/xwiki-platform-attachment-picker-test-docker/src/test/it/org/xwiki/attachment/picker/test/AttachmentPickerMacroIT.java
> +    private String computedHostURL(TestConfiguration testConfiguration)
It is probably possible to do better for this, but not sure how to get the base url to the wiki from the host.

2022-05-09 12:48 UTC, mflorea commented
The issue title says "Introduce the **grid** attachment picker macro" but I see the macro is named ``attachmentPicker``. In my view the attachment picker (selector) is all the tabs we see in the modal (gallery, tree, upload). The grid / gallery view is just one way to select / pick an attachment. So I'm wondering if we shouldn't use a more specific macro id, like ``attachmentGalleryPicker``, in order to keep ``attachmentPicker`` for the generic one that provides multiple ways to select an attachment, including the ability to upload a new attachment.

2022-05-09 13:31 UTC, mflorea requested changes

2022-05-09 13:31 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-picker/xwiki-platform-attachment-picker-war/src/main/webapp/resources/uicomponents/widgets/attachmentPicker.css
> +#template('colorThemeInit.vm')
I'd rather move this CSS to the WebJar and use LESS instead of Velocity.

2022-05-09 13:52 UTC, manuelleduc commented on xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-picker/xwiki-platform-attachment-picker-macro/src/main/java/org/xwiki/attachment/picker/AttachmentPickerMacroParameters.java
> +    @PropertyDescription("The maximum number of attachments to display")
What should I change here?
- Update the property description?
- Set a default value to the limit field?

2022-05-09 14:10 UTC, manuelleduc commented on xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-picker/xwiki-platform-attachment-picker-macro/src/main/java/org/xwiki/attachment/picker/internal/AttachmentPickerMacro.java
> +    @Named("ssfx")
What should be the parameters when calling use on a `"linkx"`? The only examples I can find are called from velocity template and the first parameter is resolved using `services.webjars.url` that I can't really call from a java macro.

2022-05-10 07:53 UTC, manuelleduc commented on xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-picker/xwiki-platform-attachment-picker-macro/src/main/java/org/xwiki/attachment/picker/internal/AttachmentPickerMacro.java
> +    @Named("ssfx")
Replaced by a less StyleSheetExtension in the ui module.

2022-05-10 08:01 UTC, manuelleduc commented on xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-picker/xwiki-platform-attachment-picker-macro/src/main/java/org/xwiki/attachment/picker/AttachmentPickerMacroParameters.java
> +    @PropertyDescription("The maximum number of attachments to display")
Default value defined https://github.com/xwiki/xwiki-platform/pull/1832/files#diff-13f051a374e20007b49930541a57446e4eb05a6c3b4a01d896ad859943b88d13R43

2022-05-10 08:04 UTC, manuelleduc commented on xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-picker/xwiki-platform-attachment-picker-macro/src/main/java/org/xwiki/attachment/picker/internal/AttachmentPickerMacro.java
> +    @Named("ssfx")
ssx call: https://github.com/xwiki/xwiki-platform/pull/1832/files#diff-5631653a669bef1a6af869909759bdf64d7a3958052e34616a95493b36fd2a31R99
less stylesheet declaration: https://github.com/xwiki/xwiki-platform/pull/1832/files#diff-a93892ccc8c4d6840de39eb370edf8da113e0f56b73ac2ed8cb463ca279f367cR250

2022-05-10 08:05 UTC, manuelleduc commented on xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-picker/xwiki-platform-attachment-picker-war/src/main/webapp/resources/uicomponents/widgets/attachmentPicker.js
> +    'xwiki-attachments-icon': $xwiki.getSkinFile('uicomponents/attachments/icons.js', true)
javascript.vm: https://github.com/xwiki/xwiki-platform/pull/1832/files#diff-93260ff9bb435e981116d60381b16f322dff457b5a9be21c0102ebcbc9d78db0R88
attachmentGridPicker UIXP: https://github.com/xwiki/xwiki-platform/pull/1832/files#diff-a93892ccc8c4d6840de39eb370edf8da113e0f56b73ac2ed8cb463ca279f367cR464

2022-05-11 07:32 UTC, mflorea requested changes

2022-05-11 07:32 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-picker/xwiki-platform-attachment-picker-ui/pom.xml
> +      <artifactId>application-ckeditor-ui</artifactId>
I'd add a comment explaining why we need this dependency and why it's optional.

2022-05-11 07:32 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-picker/xwiki-platform-attachment-picker-ui/src/main/resources/Attachment/Picker/Code/AttachmentGalleryPicker.xml
> +// End JavaScript-only code.
This looks like a leftover, and the anonymous function (wrapper) is not needed anymore.

2022-05-11 07:32 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-picker/xwiki-platform-attachment-picker-webjar/src/main/webjar/attachmentGalleryPicker.js
> +          preview = $(`<img />`)
No need for a template literal here, probably a leftover.

2022-05-11 07:32 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-attachment/xwiki-platform-attachment-picker/xwiki-platform-attachment-picker-webjar/src/main/webjar/attachmentGalleryPicker.js
> +        const link = $(`<a></a>`)
Same, no need for a template literal.

2022-05-11 07:57 UTC, merged