XWIKI-20767: TemplatesAdministrationSectionPage#createPagesFromTemplate is flickering
xwiki/xwiki-platform pull request #2128
Opened 2023-03-22 16:35 UTC by Sereza7

**Jira:** https://jira.xwiki.org/browse/XWIKI-20767

**PR Changes:**
* Workaround to fix the form submission button click.

2023-03-22 16:39 UTC, michitux requested changes
I'm not sure this really fixes the original flicker. Therefore, I wouldn't remove the wait for the live validation. Also note that you shouldn't create Jira issues for test failures unless it's a flicker you're not going to fix.

2023-03-22 16:39 UTC, michitux commented on xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-pageobjects/src/main/java/org/xwiki/administration/test/po/TemplatesAdministrationSectionPage.java
> -        this.createButton.click();
I'm not sure it is a good idea to remove the wait for the live validation. This is a different issue around blocking the submission of the button, not that something doesn't wait afterwards. Iirc the screenshots clearly showed that the submission didn't happen (you could check if there is a recent run with the failure).

2023-03-22 16:39 UTC, manuelleduc commented on xwiki-platform-core/xwiki-platform-administration/xwiki-platform-administration-test/xwiki-platform-administration-test-pageobjects/src/main/java/org/xwiki/administration/test/po/TemplatesAdministrationSectionPage.java
> +        return;
The return is not needed.
```suggestion
```

2023-03-23 16:34 UTC, michitux approved these changes

2023-03-23 16:37 UTC, merged