XWIKI-20757: CK Editor loading form element doesn't have a label
xwiki/xwiki-platform pull request #2143
Opened 2023-04-06 07:45 UTC by Sereza7

**PR Changes:**
* Added the label to the parameters of the loading textarea as a `title` and `aria-label`
* Added a translation for the label

**Note:** 
The translation key name might be not precise enough, I tried to keep consistency with `ckeditor.content.placeholder`

2023-05-03 15:04 UTC, Sereza7 commented on xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/VelocityMacros.xml
> +  #set ($loaderDescription = $escapetool.xml($services.localization.render("ckeditor.loader.placeholder")))
Thanks for the help! You're right, it was already escaped on L220 of this file, where it serialized the map to HTML. I fixed it in the latest commit :+1:

2023-05-03 15:21 UTC, Sereza7 commented
**PR Changes:**
* Removed a double escaping

**Note:** Ran a full build of `xwiki-platform-ckeditor-test` that passed. [Logs](https://up1.xwikisas.com/#RNQvlJiZM-AbZv6Gb1R8jA)

2023-05-04 12:13 UTC, manuelleduc approved these changes

2023-05-04 14:06 UTC, mflorea requested changes
I don't think this is the right fix. See my comment on https://jira.xwiki.org/browse/XWIKI-20757 .

2024-04-04 07:57 UTC, closed without merging