XWIKI-21191: Add support for uploading an attachment from the link quick action
xwiki/xwiki-platform pull request #2295
Opened 2023-08-16 09:28 UTC by douakli

Jira: https://jira.xwiki.org/browse/XWIKI-21191

This pull request adds an attachment upload entry in the link autocomplete/quick action.
Here's a preview of the feature:
![link-upload](https://github.com/xwiki/xwiki-platform/assets/132468278/af249321-06cc-4c01-a781-cb8837fa55ac)

Thanks.

2023-08-17 10:27 UTC, mflorea requested changes

2023-08-17 10:27 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-link/plugin.js
> +            require(['jquery'], function ($) {
You don't need this. You can assume jQuery is loaded already. See the ``var $ = jQuery;`` line at the start.

2023-08-17 10:27 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-link/plugin.js
> +                          }, editor);
Unusual indenting. I guess you're indenting relative to the start of the constant name, but we normally indent relative to the start of the line (everywhere else).

2023-08-17 10:27 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-link/plugin.js
> +                    `${attachment.name}</a>`);
You don't need to concatenate the lines when using the **multiline** (template) syntax. But, more importantly, you're missing XML escaping for attachment name and the attachment name also needs special escaping in the reference syntax.

```suggestion
                    editor.insertHtml($('<a></a>').attr({
                      href: attachmentURL,
                      'data-reference': CKEDITOR.plugins.xwikiResource.serializeResourceReference({
                        typed: true,
                        type: 'attach',
                        reference: attachment.name
                      })
                    }).text(attachment.name).prop('outerHTML'));
```

2023-08-18 10:49 UTC, douakli commented on xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-ui/src/main/resources/CKEditor/EditSheet.xml
> +      mentions: [],
Thanks. We don't need the empty mentions here because we check for it anyways in the plugins.
So I should just remove it I suppose.

2023-08-18 12:54 UTC, mflorea reviewed
Looks good. Only two minor comments.

2023-08-18 12:54 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-link/plugin.js
> +            // // Upload attachment item should be the first in the list.
```suggestion
            // Upload attachment item should be the first in the list.
```

2023-08-18 12:54 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-ckeditor/xwiki-platform-ckeditor-plugins/src/main/webjar/xwiki-link/plugin.js
> +                  return Promise.reject();
Is this needed? You don't chain anything after the ``catch`` call, and you don't return the promise either.

2023-08-18 13:08 UTC, mflorea approved these changes

2023-08-18 13:09 UTC, merged