Xwiki 12824
xwiki/xwiki-platform pull request #2831
Opened 2024-01-30 15:23 UTC by Sereza7

# Jira URL

https://jira.xwiki.org/browse/XWIKI-12824

# Changes

## Description

* Added content for toggler buttons in appropriate templates
* Added style changes / updates in layout.less
* Added a javascript source to handle the interactivity of those togglers.

## Clarifications

* I tried adding transitions for the panels, but this is a really tough thing with both bootstrap columns and `display: none` that complicate things. In the end, I just added an animation for the panels flying out when collapsed. Everything else is instantaneous transitions (it might become more manageable once `@starting-style` is supported on Firefox)

# Screenshots & Video

[Here is a demo of the feature](https://youtu.be/COQJpBQen1Q) on a clean 16.1.0-snapshot instance.
# Executed Tests

None yet. Build in progress.
# Expected merging strategy

* Prefers squash: Yes 
* Backport on branches:
  * None. It's a new feature that could bring problems in some custom UIs relying on old classes of the body. I changed the way these classes were used for style, with minimal changes, but it's still an update that could break some custom style (eg, now the body classes can be changed on the run, while before they were sert once and for all at page load).

2024-07-11 13:20 UTC, Sereza7 commented
Converted to a draft until the comments from the forum topic have been integrated in the UI :)

2025-01-03 16:55 UTC, Sereza7 commented
See https://forum.xwiki.org/t/ui-proposal-panel-column-togglers/15063/22 for the forum discussion

2025-03-21 16:55 UTC, Sereza7 commented
Here is a demo of the feature. AFAICS, everything looks and behaves as expected now.
https://github.com/user-attachments/assets/f823f92b-c5bc-41b7-94a2-5a2603c0d606

2025-04-29 15:39 UTC, Sereza7 commented
Here is a video demo of manual changes made until https://github.com/xwiki/xwiki-platform/pull/2831/commits/2c407445866482db6a0a1533b081655a5ac2aa05 :


https://github.com/user-attachments/assets/bfdf4c68-a257-4cf3-a690-8c032831b6de

We can see in this video that:
* The state of the panels is stored in localstorage
* This state is shared across tabs on the same machine
* Closing and reopening the panel will reset the width of the panel column. It interacts as expected with the way we save the width preference.

2025-05-05 08:57 UTC, mflorea requested changes

2025-05-05 08:57 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/flamingo.js
> +  animation before hiding it. */
```suggestion
  // The body update hides completely the panel column. We want to make sure the panel column is visible for the whole
  // animation before hiding it.
```

2025-05-05 08:57 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/flamingo.js
> +    let showRightColumn = showSide(side, newExpandedState, left);
```suggestion
    let showRightColumn = showSide(side, newExpandedState, right);
```

2025-05-05 08:57 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/flamingo.js
> +    if (!showLeftColumn && !showRightColumn) bodyClasses.add('hidelefthideright');
```suggestion
    bodyClasses.toggle('hidelefthideright', !showLeftColumn && !showRightColumn);
```

2025-05-05 08:57 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/flamingo.js
> +    if (!showLeftColumn && showRightColumn) bodyClasses.add('hideleft');
```suggestion
    bodyClasses.toggle('hideleft', !showLeftColumn && showRightColumn);
```

2025-05-05 08:57 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/flamingo.js
> +    if (showLeftColumn && !showRightColumn) bodyClasses.add('hideright');
```suggestion
    bodyClasses.toggle('hideright', showLeftColumn && !showRightColumn);
```

2025-05-05 08:57 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/flamingo.js
> +  var togglePanels = function (side) {
```suggestion
  let togglePanels = function (side) {
```

2025-05-05 08:57 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/flamingo.js
> +      else {
```suggestion
      } else {
```

2025-05-05 08:57 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/leftpanels.vm
> +    <div class="sr-only">$services.localization.render('panels.column.toggle.left.label')</div>
Where is ``panels.column.toggle.left.label`` defined?

2025-05-05 08:57 UTC, mflorea commented on xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/rightpanels.vm
> +    <div class="sr-only">$services.localization.render('panels.column.toggle.right.label')</div>
Same, I don't see where ``panels.column.toggle.right.label`` is defined.

2025-05-05 13:41 UTC, Sereza7 commented on xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/flamingo.js
> +    if (!showLeftColumn && !showRightColumn) bodyClasses.add('hidelefthideright');
Thanks! This syntax is way shorter and easier to read.

2025-05-05 13:57 UTC, Sereza7 commented on xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/leftpanels.vm
> +    <div class="sr-only">$services.localization.render('panels.column.toggle.left.label')</div>
My bad, it was meant to be the same key as above. When I went over the key names to make them more consistent, I missed that it was used twice for each toggle and only updated the one in the title attribute. Fixed in https://github.com/xwiki/xwiki-platform/pull/2831/commits/860aefca81390e3ee26abfcec00fc9c5eac582ce :+1:

2025-05-05 13:59 UTC, Sereza7 commented on xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/flamingo.js
> +  animation before hiding it. */
https://dev.xwiki.org/xwiki/bin/view/Drafts/Javascript%20Code%20Style/ :+1: 

```
Multiline comments are reserved to document functions (methods) and classes (or types in general). For other kinds of comments, use two forward slashes.
```

2025-05-06 08:55 UTC, merged