XWIKI-20616: Update jstree files and remove reference to throbber.gif
xwiki/xwiki-platform pull request #2913
Opened 2024-02-20 10:38 UTC by amottier

# Jira URL

https://jira.xwiki.org/browse/XWIKI-20616

# Changes

## Description

* Update files provided by `jstree` to use the ones provided in version `3.3.16` (version of `jstree` referenced in the `pom.xml`).
* Comment out the reference to `throbber.gif` in `jstree` `mixins.less` file as the gif file is no part of `xwiki-platform-tree-webjar` and rule is override in `tree.less` to use `spinner.gif`.

## Clarifications

* By looking at files such as [`xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/less/jstree/mixins.less`](https://github.com/xwiki/xwiki-platform/blob/52e78eb4d31a8b449cd9422412edb947df0f71c1/xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/less/jstree/mixins.less) it appears they were part of version `3.3.5` or earlier (see for example this [diff](https://github.com/vakata/jstree/compare/3.3.5..3.3.6#diff-c6eea180a2a3a75378b36f8ba3d678924453a910d9c7fe1d5a7a0fd6721405ac) of `src/themes/mixins.less` file between version `3.3.5` and `3.3.6`). As [`pom.xml` specifies version `3.3.16`](https://github.com/xwiki/xwiki-platform/blob/52e78eb4d31a8b449cd9422412edb947df0f71c1/xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/pom.xml#L37) this commit update files included in `xwiki-platform-tree-webjar` that are coming from `jstree` project.
* Removing the reference to `throbber.gif` is a way to remove warning in the log that are probably triggered by search bot parsing the CSS. This doesn't seems to trigger any issue in XWiki with normal user interaction.

# Executed Tests

`./mvnw -Psnapshot,dev clean install -f xwiki-platform-core/xwiki-platform-tree/pom.xml` (with Java 17 and Maven 3.9.6)

2024-02-20 13:14 UTC, surli commented
> By looking at files such as [xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/less/jstree/mixins.less](https://github.com/xwiki/xwiki-platform/blob/52e78eb4d31a8b449cd9422412edb947df0f71c1/xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/less/jstree/mixins.less) it appears they were part of version 3.3.5 or earlier (see for example this [diff](https://github.com/vakata/jstree/compare/3.3.5..3.3.6#diff-c6eea180a2a3a75378b36f8ba3d678924453a910d9c7fe1d5a7a0fd6721405ac) of src/themes/mixins.less file between version 3.3.5 and 3.3.6). As [pom.xml specifies version 3.3.16](https://github.com/xwiki/xwiki-platform/blob/52e78eb4d31a8b449cd9422412edb947df0f71c1/xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/pom.xml#L37) this commit update files included in xwiki-platform-tree-webjar that are coming from jstree project.

@mflorea apparently you performed the upgrade from jstree 3.3.5 to 3.3.7 in https://github.com/xwiki/xwiki-platform/commit/ced2f2cc1d2141e5170ca76653fca71a45ef801b did you forgot to update those files back then? Maybe we need some specific instructions for upgrading these?

2024-02-29 16:31 UTC, amottier commented
@surli @mflorea is there anything I can do on my side to help the merge of this PR? Don't hesitate to reach out if I can assist. Thanks.

2024-07-24 12:14 UTC, mflorea requested changes
You're removing customizations that we did on top of jstree. Unfortunately they are not marked so it's not easy to spot them unless you make a diff between our version of the jstree less files and the original jstree less files.

2024-07-24 12:35 UTC, amottier commented on xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/less/jstree/mixins.less
> -	.jstree-ellipsis.jstree-no-icons .jstree-anchor { width: calc(100% ~"-" 5px); }
Actually it seems this line was removed upstream in version `3.3.6` : https://github.com/vakata/jstree/compare/3.3.5..3.3.6#diff-c6eea180a2a3a75378b36f8ba3d678924453a910d9c7fe1d5a7a0fd6721405ac

2024-07-24 12:36 UTC, amottier commented on xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/less/jstree/main.less
> +	.jstree-clicked { background:@clicked-bg-color; border-radius:2px; box-shadow:inset 0 0 1px @clicked-shadow-color; }
I agree I'll restore this change.

2024-07-24 12:38 UTC, amottier commented on xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/less/jstree/main.less
> +		> .jstree-icon { opacity:0.8; filter: url("data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'jstree-grayscale\'><feColorMatrix type=\'matrix\' values=\'0.3333 0.3333 0.
I agree I'll restore this change.

2024-07-24 12:41 UTC, amottier commented on xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/less/jstree/base.less
> +.jstree-icon { display:inline-block; text-decoration:none; margin:0; padding:0; vertical-align:top; text-align:center; }
I agree I'll restore this change.

2024-07-24 12:41 UTC, amottier commented on xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/less/jstree/base.less
> -}
I agree I'll restore this change.

2024-07-24 12:47 UTC, amottier commented on xwiki-platform-core/xwiki-platform-tree/xwiki-platform-tree-webjar/src/main/less/jstree/base.less
> -}
I agree I'll restore this change.

2024-07-24 13:51 UTC, amottier commented
@mflorea hopefully I restored all customization that I accidentally removed. This pull request is again ready for review. Thanks for your help :+1:

2024-07-26 11:48 UTC, mflorea approved these changes
Looks good to me. Thanks a lot for your contribution and for your patience.

2024-07-26 11:49 UTC, merged

2024-07-29 08:10 UTC, amottier commented
Thanks a lot for accepting the pull request and for taking the time to review it :+1: