XWIKI-22169: Breadcrumb dropdowns for navigation should be keyboard accessible
xwiki/xwiki-platform pull request #3376
Opened 2024-08-29 09:55 UTC by Sereza7

# Jira URL

https://jira.xwiki.org/browse/XWIKI-22169
# Changes

## Description

* Added a label to the tree toggler button

## Clarifications

* The label uses the name of the page where the tree should be opened to.
* This label is here for AT only - it does not change the visuals.

# Screenshots & Video

![Screenshot from 2024-08-28 14-01-50](https://github.com/user-attachments/assets/f60ecf27-2ce7-4aca-9220-2ad37a0d6d32)

We can see on the screenshot that the three togglers have labels that do reflect their actions correctly.

# Executed Tests

Manual tests similar to https://github.com/xwiki/xwiki-platform/pull/3120
Successfully fixed `mvn clean install -f xwiki-platform-core/xwiki-platform-image/xwiki-platform-image-style/xwiki-platform-image-style-test/xwiki-platform-image-style-test-docker -Pdocker -Dxwiki.enforcer.skip=true -Dxwiki.test.ui.wcag=true -Dit.test=ImageStyleIT#imageStyleAdministration` after building the changes with `mvn clean install -f xwiki-platform-core/xwiki-platform-web`.

# Expected merging strategy

* Prefers squash: Yes 
* Backport on branches:
  * 15.10.X, 16.4.X, same as https://github.com/xwiki/xwiki-platform/pull/3120

2024-08-29 12:03 UTC, michitux requested changes

2024-08-29 12:03 UTC, michitux commented on xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/hierarchy_macros.vm
> +      #set ($togglerTextAlternative = "<span class='sr-only'>$services.localization.render('web.hierarchy.toggler.label.children', [$pathData.get($openToIndex).label]) </span>")
This translation needs to be escape, in particular the parameter as otherwise this is vulnerable to XSS if not XWiki syntax injection/remote code execution.

2024-08-29 12:03 UTC, michitux commented on xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/hierarchy_macros.vm
> +      #set ($togglerTextAlternative = "<span class='sr-only'>$services.localization.render('web.hierarchy.toggler.label.parents', [$pathData.get($openToIndex).label]) </span>")
Same here, this is missing escaping.

2024-08-30 08:18 UTC, Sereza7 commented
@michitux https://github.com/xwiki/xwiki-platform/pull/3376/commits/cae0a44b7b6b57740cfb67431bff6ab32929a9cd should take care of the escaping for both of those :+1:

2024-08-30 08:20 UTC, michitux requested changes

2024-08-30 08:20 UTC, michitux commented on xwiki-platform-core/xwiki-platform-web/xwiki-platform-web-templates/src/main/resources/templates/hierarchy_macros.vm
> +      $escapetool.xml($unescapedTogglerTextAlternative) +
So we'll now have a visible label that starts with `<span`? Not good.

2024-08-30 08:26 UTC, Sereza7 commented
I did not properly test things:
![Screenshot from 2024-08-30 10-23-52](https://github.com/user-attachments/assets/6b461c9f-36d8-4a00-8070-8221147f85b2)
With the changes in https://github.com/xwiki/xwiki-platform/pull/3376/commits/c18fe20f547a05c01983302ab5c4c731c1fa5d31 :
![Screenshot from 2024-08-30 10-25-10](https://github.com/user-attachments/assets/7ade5e96-572e-4675-9557-47a8027633ab)

2024-08-30 08:34 UTC, merged